users = [
  { aoc = 644309, matrix = "@defelo:matrix.defelo.de", repo = "https://github.com/Defelo/AdventOfCode" },
  { aoc = 644683, matrix = "@tnt2k:matrix.org", repo = "https://github.com/TheCataliasTNT2k/adventofcode" },
  { aoc = 1059924, matrix = "@loc:locrealloc.de", repo = "https://github.com/LoCrealloc/aoc2022" },
  { aoc = 1040905, matrix = "@wolflu:matrix.org", repo = "https://github.com/wolflu05/AdventOfCode" },
  { aoc = 1506869, matrix = "@inarius:matrix.org" },
  { aoc = 1577801, matrix = "@mik:fbsweb.de" },
  { aoc = 2393329, matrix = "@felix:beichler.eu" },
  { aoc = 1067631, repo = "https://github.com/Scriptim/AdventOfCode2021" },
  { aoc = 971212, repo = "https://gitlab.com/McModknower/advent-of-code-lisp" },
  { aoc = 527018, repo = "https://github.com/Blauelf/AdventOfCode" },
  { aoc = 1244156, repo = "https://github.com/Tristan-H11/AdventOfCode21" },
  { aoc = 2337460, repo = "https://github.com/tanypteryx/AdventOfCode" },
  { aoc = 1055972, repo = "https://github.com/DerDomee/adventofcode-typescript" },
  { aoc = 999860, matrix = "@shrumpf:matrix.org", repo = "https://github.com/Shrumpf/advent-of-code" },
  { aoc = 1090750, repo = "https://gitlab.com/AtticusSullivan/adventofcode" },
  { aoc = 1046310, repo = "https://github.com/TheMorpheus407/AdventOfCode2020" },
  { aoc = 1069020, repo = "https://github.com/itsCryne/aoc2021" },
  { aoc = 3408681, matrix = "@marcel:envs.net", repo = "https://codeberg.org/m4rc3l/aoc-2024" },
  { aoc = 1061494, repo = "https://github.com/Marc55s/AdventOfCode2021" },
  { aoc = 1188170, repo = "https://github.com/Keksnet/advent-of-code-21" },
  { aoc = 996295, repo = "https://github.com/Ari24-cb24/adventofcodeanswers" },
  { aoc = 1070766, repo = "https://github.com/Mango-de/advent-of-code-2023" },
  { aoc = 1553036, repo = "https://github.com/niklasschloegel/advent-of-code-2021" },
  { aoc = 1505083, repo = "https://github.com/leonfroschauer/AdventOfCode/tree/main/2021" },
  { aoc = 1591154, repo = "https://github.com/vKxni/aoc-ex" },
  { aoc = 2318405, repo = "https://github.com/0x3alex/AoC22" },
  { aoc = 2336338, repo = "https://github.com/Pythonwolf7734/AdventOfCode" },
  { aoc = 976466, repo = "https://github.com/YAWNICK/AoC" },
  { aoc = 2356146, repo = "https://github.com/TheKogs/AdventOfCode" },
  { aoc = 1643403, repo = "https://github.com/TheBlckbird/advent_of_code" },
  { aoc = 2458351, repo = "https://github.com/Maschga/Advent-of-Code-Solutions" },
  { aoc = 205092, matrix = "@vo-coder:matrix.org" },
  { aoc = 1561991, matrix = "@lilith:matrix.firelilith.org", repo = "https://git.firelilith.org/lilith/aocrust" },
]
